
package com.mycompany.jogodadosengsoft;

import javax.swing.JOptionPane;


public class JogoDadosGui extends javax.swing.JFrame {

    /**
     * Creates new form JogoDados
     */
    public JogoDadosGui() {
        String caminho = getClass().getProtectionDomain().getCodeSource().getLocation() + "com/mycompany/logo.png";
        System.out.println("classe" + getClass().getResource(caminho));
        jogo = new Jogo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inserirNome = new javax.swing.JButton();
        inserirNome1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jogarDados = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        valorDado1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        valorDado2 = new javax.swing.JLabel();
        somaFaces = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jogador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(74, 154, 233));
        jPanel1.setForeground(new java.awt.Color(74, 154, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atividade de engenharia de software");

        inserirNome.setBackground(new java.awt.Color(152, 195, 237));
        inserirNome.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        inserirNome.setForeground(new java.awt.Color(255, 255, 255));
        inserirNome.setText("Inserir nome");
        inserirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNomeActionPerformed(evt);
            }
        });

        inserirNome1.setText("Inserir nome");
        inserirNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(270, 270, 270)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inserirNome)
                    .addComponent(inserirNome1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inserirNome))
                .addGap(14, 14, 14)
                .addComponent(inserirNome1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(74, 154, 233));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(152, 195, 237));
        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/logo.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(260, 10, 200, 200);

        jogarDados.setBackground(new java.awt.Color(74, 154, 233));
        jogarDados.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jogarDados.setForeground(new java.awt.Color(255, 255, 255));
        jogarDados.setText("Jogar dados");
        jogarDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jogarDados.setPreferredSize(new java.awt.Dimension(150, 40));
        jogarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarDadosActionPerformed(evt);
            }
        });
        jPanel3.add(jogarDados);
        jogarDados.setBounds(280, 230, 150, 40);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        valorDado1.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        valorDado1.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(valorDado1)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(valorDado1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(220, 300, 100, 100);

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel5.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));

        valorDado2.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        valorDado2.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(valorDado2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(valorDado2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(400, 300, 100, 100);

        somaFaces.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        somaFaces.setText("0");
        jPanel3.add(somaFaces);
        somaFaces.setBounds(450, 430, 30, 42);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("A soma da faces é:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(230, 430, 210, 42);

        resultado.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        resultado.setText("Resultado:");
        resultado.setMaximumSize(new java.awt.Dimension(170, 100));
        resultado.setMinimumSize(new java.awt.Dimension(170, 100));
        jPanel3.add(resultado);
        resultado.setBounds(150, 500, 430, 42);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 50, 52, 22);

        jogador.setBackground(new java.awt.Color(0, 0, 0));
        jogador.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jogador.setText("Jogador");
        jPanel3.add(jogador);
        jogador.setBounds(80, 50, 170, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarDadosActionPerformed
        // TODO add your handling code here:
        
        // Chama o metodo jogar para iniciar o jogo
        jogo.jogar();
        
        // Armazena os dados lançados
        Dado[] dados = jogo.getDados();
        
        // Atirbui a variavel face1 o valor da face do primeiro dado
        String face1 = String.valueOf(dados[0].getFace());
        
        // Atribui a variavel face2 0 valor da face do segundo dado
        String face2 = String.valueOf(dados[1].getFace());
        
        // Adiciona aos textos da interface grafico as faces dos dados
        valorDado1.setText(face1);
        valorDado2.setText(face2);
        
        // Armazena a soma das faces dos dados lançados
        String somaFacesDados = String.valueOf(jogo.getSomaFaces());
        
        // Adiciona a interface gráfica a soma das faces dos dados lançados
        somaFaces.setText(somaFacesDados);
        
        // Exibe o resultado do jogo
        resultado.setText(jogo.obterResultado());
        
    }//GEN-LAST:event_jogarDadosActionPerformed

    private void inserirNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirNome1ActionPerformed

    private void inserirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNomeActionPerformed
        // TODO add your handling code here:
        
        // Mostra uma mensagem ao usuario para escrever seu nome e o armazena na variavel nome
        String nome = JOptionPane.showInputDialog("Qual é o seu nome?");
        
        // Instancia um objeto do tipo Jogador
        Jogador jogador = new Jogador();
        
        // Armazena ao jogador o seu nome
        jogador.setNome(nome);
        
        // Adiciona ao atributo jogador da classe jogo, a instancia de jogador
        jogo.setJogador(jogador);
        
        // Adiciona a interface gráfica o nome do jogador
        this.jogador.setText(nome);
    }//GEN-LAST:event_inserirNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inserirNome;
    private javax.swing.JButton inserirNome1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jogador;
    private javax.swing.JButton jogarDados;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel somaFaces;
    private javax.swing.JLabel valorDado1;
    private javax.swing.JLabel valorDado2;
    // End of variables declaration//GEN-END:variables
    private Jogo jogo;
}
